require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
#kakao-login을 사용하려면 최소 11이어야 하는데요?? 찾아보니 ios 12이상이 91%라고 합니다 어린 친구들은 더 높겠죠?
target 'swaApp' do
  use_unimodules!
  # use_flipper!({'Flipper' => '0.74.0'})
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  # add the Firebase pod for Google Analytics
  # pod 'Firebase/Analytics'
  # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Firebase/InAppMessaging'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
end